### PR TITLE
Use proper key for OSX comment keybind

### PR DESCRIPTION
**Pull request by Whoaa512**

### CODE REVIEW

**Comment by borela** [comment]
Thank you! I wasn't sure if the shortcuts were correct on OSX.

**Comment by borela** [comment]
Forgot to say, feel free to add your name in one of the licenses in a subsequent pull request or just tell me here your name, email and desired license to add it.

**Comment by Whoaa512** [comment]
Name is CJ Winslow, email is whoaa512@gmail.com, MIT is fine with me

**Comment by borela** [comment]
Added https://github.com/borela/naomi/blob/master/LICENSE-MIT.md thank you :D

**Pull request merged**
