### PR TITLE
Distinguish Naomi syntax names from others

### PR DESCRIPTION
**Pull request by TomasBarry**

### CODE REVIEW

**Comment by borela** [comment]
In the beginning I used similar names to the core's syntaxes to make it compatible with other plugins that rely on the syntaxes' names, I'll take a look if it does not break them.

**Comment by TomasBarry** [comment]
Hi @borela, what I've done for a while now is just update the names in the downloaded package but then any update that was pushed to the package overwrote my changes so I thought it'd be best to make a PR for this.

WRT to the failed travis check, you'll have to point me in the right direction in fixing those test errors.

**Comment by borela** [comment]
Don't worry about the travis errors, that's not caused by your patch, for the past 3 months I've been updating the scopes to enhance the compatibility with the core syntaxes and it broke many tests.

Your patch is something that I wanted to do for a long time, sometimes people get confused if they are in fact using these syntaxes because the names are too similar. I just have to check some plugins but I believe this change is fine.

**Comment by TomasBarry** [comment]
@borela, sounds good. Fixed one travis issue FWIW anyway in this PR.

Hopefully there are no issues. This is a heavily used project in my team.

**Comment by borela** [comment]
I tried to use some plugins and this change doesn't seam to affect them. Thank you! :D

**Comment by borela** [comment]
Forgot to ask you to write your name and email in one of the licenses, which one do you want?

**Comment by TomasBarry** [comment]
How long does it typically take before the package is updated on Package Control?

**Comment by borela** [comment]
About ~3h max after I tag a commit, don't need to need a new pull request, I'll send a patch to the [MIT license](https://github.com/borela/naomi/blob/master/LICENSE-MIT.md). Do you want to add the email on your profile or do you have another one that you prefer?

**Comment by StreetStrider** [comment]
That was needed indeed. Previously Naomi's sytaxes was indistinguishable from default ones both in status bar (current) and in command palette (when you apply them).

**Comment by TomasBarry** [comment]
tomas.barry@hotmail.com will do just fine @borela, have you tagged the commit yet?

**Comment by borela** [comment]
Modified the license and tagged the commit https://github.com/borela/naomi/releases/tag/v4.1.1 considering package control crawled the repo 40 minutes ago, it should update in about 2:30h.

**Comment by TomasBarry** [comment]
Brilliant. Thanks @borela

**Comment by StreetStrider** [comment]
@borela @TomasBarry after update, my snippets (located under `Packages/JavaScript/`, and with scope `source.js`) stop working. How do I inherit them to work for `JavaScript (Naomi)` as well?

**Comment by borela** [comment]
@StreetStrider It should continue to work as expected, try cleaning the cache directories:

* OS X: `~/Library/Application Support/Sublime Text 3`
* Windows: `%LOCALAPPDATA%\Sublime Text 3`
* Linux: `~/.config/sublime-text-3`

**Comment by borela** [comment]
Another thing I did, I excluded the node_modules directory, I usually have many projects open and that was screwing the indexer for me, this is my settings:

```json
{
	"auto_id_class": true,
	"color_scheme": "Packages/Naomi/Candyman.tmTheme",
	"draw_shadows": false,
	"draw_white_space": "selection",
	"ensure_newline_at_eof_on_save": true,
	"folder_exclude_patterns":
	[
		".svn",
		".git",
		".hg",
		"CVS",
		"*/node_modules"
	],
	"font_face": "Monaco",
	"font_size": 15,
  	"ignored_packages":
	[
		"Six",
		"Vintage",
		"Vintageous"
	],
	"indent_guide_options":
	[
		"draw_active"
	],
	"index_files": false,
	"preview_on_click": false,
	"rulers":
	[
		80,
		120
	],
	"show_encoding": true,
	"show_line_endings": true,
	"skin": "DA UI/Classic",
	"theme": "DA.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"vintageous_use_ctrl_keys": true,
	"vintageous_use_sys_clipboard": true
}

**Comment by StreetStrider** [comment]
@borela my issue somehow resolved.

On the offtopic note, are you sure `folder_exclude_patterns` supports globbing? As far as I used it in my `sublime-project` settings, it's pretty dumb and does not recognize any nesting/globbing.

**Comment by borela** [comment]
@StreetStrider It does but you are correct in the fact that in that case, `node_modules` and `*/node_modules` have the same effect, I did some tests targeting a folder under another one e.g.: `modules/**/foo` and the globbing worked as expected.

**Comment by StreetStrider** [comment]
@borela nice to hear that. I had issues when I got directory `release/` with generated files which I want to ignore and `src/release` or something like, which is legit src files. They all got banned by simple `release` pattern (obviously), but I tried to improve globbing and it just stops ignoring at all. I will re-iterate this, maybe recent ST3 release finally improved that.

**Comment by borela** [comment]
@StreetStrider I see what you mean, you need negation and that is not working as expected, found some issues on the topic :/

https://github.com/SublimeTextIssues/Core/issues/1895
https://github.com/SublimeTextIssues/Core/issues/1897

**Comment by StreetStrider** [comment]
@borela, yes, that's the case exactly.

**Pull request merged**
